repos:
  - repo: local
    hooks:
      - id: cpp-build
        name: Build C++ code
        entry: g++
        language: system
        files: 'processes/*\.cpp$'
        stages: [ pre-push ]

      - id: ruff-format
        name: Ruff format
        entry: ruff format
        language: system
        types: [ python ]
        stages: [ pre-commit ]

      - id: ruff-check-and-fix
        name: Ruff check and fix
        entry: ruff check
        args: [ --fix ]
        language: system
        types: [ python ]
        stages: [ pre-commit ]

      - id: mypy-type-check
        name: MyPy type check
        entry: mypy
        language: system
        types: [ python ]
        stages: [ pre-commit ]

  - repo: "https://github.com/astral-sh/uv-pre-commit"
    rev: 0.8.13
    hooks:
      - id: uv-lock
        name: Update uv.lock
        stages: [ pre-commit ]
