name: pytest tests
permissions:
  contents: read
  pull-requests: read

on:
  push:
    paths:
      - ".github/workflows/linters.yaml"
      - "**.py"
  pull_request:
    paths:
      - ".github/workflows/linters.yaml"
      - "**.py"

jobs:
  pytest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true

      - name: Install deps
        working-directory: fs
        run: uv sync --frozen

      - name: Run MyPy
        working-directory: fs
        run: pytest CourseOS/tests
