name: UI compilation
permissions:
  contents: read
  pull-requests: read

on:
  push:
    paths:
      - ".github/workflows/ui-compile.yaml"
      - "**.ui"
  pull_request:
    paths:
      - ".github/workflows/ui-compile.yaml"
      - "**.ui"

jobs:
  ui-compile:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
  
      - name: Install deps
        working-directory: fs
        run: uv sync --frozen --no-dev

      - name: Run pyuic
        working-directory: fs
        run: find ./src/ui/ui -type f -name *.ui -exec uv run -m PyQt6.uic.pyuic -x {} \; > /dev/null
